/*
 * This source file was generated by the Gradle 'init' task
 */
package calculadoraappconsola;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test
    void testSumar() {
        assertEquals(8, App.sumar(5, 3));
    }

    @Test
    void testRestar() {
        assertEquals(2, App.restar(10, 5));
    }

    @Test
    void testMultiplicar() {
        assertEquals(15, App.multiplicar(5, 3));
    }

    @Test
    void testDividir() { //Division entera
        assertEquals(2, App.dividir(10, 5));
    }

    @Test
    void testDividirPorCero() {
        assertThrows(ArithmeticException.class, () -> {
            App.dividir(10, 0);
        });
    }
}
